export default function About() {
    return (
        <main className="min-h-full bg-slate-100 dark:bg-slate-800 dark:text-white p-2 space-y-3">
            <h1 className="font-bold font-serif uppercase text-xl hover:underline">about</h1>
            <p>Lorem ipsum dolor sit amet consectetur adipisicing elit. Velit saepe neque fuga modi doloribus. Exercitationem debitis excepturi minus enim architecto, quis qui, porro dolorum, voluptatibus temporibus quibusdam non molestias laudantium dignissimos itaque sapiente! Autem, iure temporibus. Et nisi eum voluptatibus dolores! Facilis autem cumque, est, repudiandae unde omnis accusamus a distinctio consequatur eaque deleniti dolor necessitatibus non quos soluta fugiat quam exercitationem! Eaque sed iste eius vel maxime assumenda animi dolores pariatur architecto modi molestias, mollitia laudantium, doloremque ad, quaerat laborum non culpa perspiciatis itaque magni consectetur sequi blanditiis exercitationem voluptate? Earum animi qui quis dignissimos id fuga veritatis possimus beatae minus vel error corrupti sunt, tenetur blanditiis sapiente deleniti est et harum aspernatur neque corporis iusto saepe nam placeat. Officiis nesciunt eaque quis dolorem beatae? Rem repellendus nobis assumenda maiores optio quas, molestiae et dolore repudiandae nihil nam culpa, ipsam officia unde ipsum non sunt libero atque! Fuga, labore.</p>
            <p>Lorem ipsum dolor sit amet consectetur adipisicing elit. Velit saepe neque fuga modi doloribus. Exercitationem debitis excepturi minus enim architecto, quis qui, porro dolorum, voluptatibus temporibus quibusdam non molestias laudantium dignissimos itaque sapiente! Autem, iure temporibus. Et nisi eum voluptatibus dolores! Facilis autem cumque, est, repudiandae unde omnis accusamus a distinctio consequatur eaque deleniti dolor necessitatibus non quos soluta fugiat quam exercitationem! Eaque sed iste eius vel maxime assumenda animi dolores pariatur architecto modi molestias, mollitia laudantium, doloremque ad, quaerat laborum non culpa perspiciatis itaque magni consectetur sequi blanditiis exercitationem voluptate? Earum animi qui quis dignissimos id fuga veritatis possimus beatae minus vel error corrupti sunt, tenetur blanditiis sapiente deleniti est et harum aspernatur neque corporis iusto saepe nam placeat. Officiis nesciunt eaque quis dolorem beatae? Rem repellendus nobis assumenda maiores optio quas, molestiae et dolore repudiandae nihil nam culpa, ipsam officia unde ipsum non sunt libero atque! Fuga, labore.</p>
            <p>Lorem ipsum dolor sit amet consectetur adipisicing elit. Velit saepe neque fuga modi doloribus. Exercitationem debitis excepturi minus enim architecto, quis qui, porro dolorum, voluptatibus temporibus quibusdam non molestias laudantium dignissimos itaque sapiente! Autem, iure temporibus. Et nisi eum voluptatibus dolores! Facilis autem cumque, est, repudiandae unde omnis accusamus a distinctio consequatur eaque deleniti dolor necessitatibus non quos soluta fugiat quam exercitationem! Eaque sed iste eius vel maxime assumenda animi dolores pariatur architecto modi molestias, mollitia laudantium, doloremque ad, quaerat laborum non culpa perspiciatis itaque magni consectetur sequi blanditiis exercitationem voluptate? Earum animi qui quis dignissimos id fuga veritatis possimus beatae minus vel error corrupti sunt, tenetur blanditiis sapiente deleniti est et harum aspernatur neque corporis iusto saepe nam placeat. Officiis nesciunt eaque quis dolorem beatae? Rem repellendus nobis assumenda maiores optio quas, molestiae et dolore repudiandae nihil nam culpa, ipsam officia unde ipsum non sunt libero atque! Fuga, labore.</p>
            <p>Lorem ipsum dolor sit amet consectetur adipisicing elit. Velit saepe neque fuga modi doloribus. Exercitationem debitis excepturi minus enim architecto, quis qui, porro dolorum, voluptatibus temporibus quibusdam non molestias laudantium dignissimos itaque sapiente! Autem, iure temporibus. Et nisi eum voluptatibus dolores! Facilis autem cumque, est, repudiandae unde omnis accusamus a distinctio consequatur eaque deleniti dolor necessitatibus non quos soluta fugiat quam exercitationem! Eaque sed iste eius vel maxime assumenda animi dolores pariatur architecto modi molestias, mollitia laudantium, doloremque ad, quaerat laborum non culpa perspiciatis itaque magni consectetur sequi blanditiis exercitationem voluptate? Earum animi qui quis dignissimos id fuga veritatis possimus beatae minus vel error corrupti sunt, tenetur blanditiis sapiente deleniti est et harum aspernatur neque corporis iusto saepe nam placeat. Officiis nesciunt eaque quis dolorem beatae? Rem repellendus nobis assumenda maiores optio quas, molestiae et dolore repudiandae nihil nam culpa, ipsam officia unde ipsum non sunt libero atque! Fuga, labore.</p>
        </main>
    );
}